name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clang-format Check
        uses: jidicula/clang-format-action@v3.2.0
        with:
          # The version of clang-format that you want to use.
          clang-format-version: 11
          # The path to the directory you want to check for correct C/C++formatting. Default is the full repository.
          check-path: .
          # The fallback style for clang-format if no .clang-format file exists in your repository.
          fallback-style: Google
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: make docker_test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: coverage
        run: make docker_coverage
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: './docs/coverage.html'
          message: 'Update test coverage report.'
      # https://github.com/codecov/codecov-action
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./docs/coverage.xml
          flags: unittests
          name: codecov-umbrella

  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

